### PR TITLE
WIP: Rebase on Debian 1.14.6-2

### PR DESCRIPTION
**Pull request by lkundrak**
See how this files.

I organized the changes by bringing in the vanilla Debian package, then putting the patches back in and finally merging in the Xenial base. Should be good enough to track changes as well as seeing brid's eye of the changes in the merge commit.

What should be apparent is that I dropped some patches because they bitrotted too much.

Also, there's more stuff there to verify: e.g. removal of tests/ or the libnm-glib packages.

### CODE REVIEW

**Comment by Flohack74** [comment]
Cool I need to fire up our CI for that repo ;)

**Comment by Flohack74** [comment]
You need to set the changelog to xenial release:

UNRELEASED wont work, otherwise our CI freaks out. Just ignore usual debian rules here ;)


BR Florian

**Comment by Flohack74** [comment]
You are still good? Anything we can do to help you?

**Comment by mariogrip** [comment]
@Flohack74 I'm not sure if this will have time to get into OTA-12, and I would suggest this gets staged into edge before going directly to devel as we are pretty close to end of the development cycle.

**Comment by Flohack74** [comment]
I agree.

**Comment by Flohack74** [comment]
Due to the upgrade to 20.04 base this became a bit obsolete. We might want to revisit it later this year though.

**Pull request closed without merging**
